### PR TITLE
Update Translation of "tag"

### PR DESCRIPTION
**Pull request by oldsharp**
- "tag" translated as "标签".
- "annotated tag" translated as "注释标签".
- "mergetag" translated as "合并标签".
- "tag name" translated as "标签名称".
- Relevant adjustments.

### CODE REVIEW

**Comment by jiangxin** [comment]
Too busy these days, I will review it tonight.

**Comment by oldsharp** [comment]
Thanks.

**Comment by oldsharp** [comment]
Hi @jiangxin , the community of _Pro Git 2nd_ zh_CN translation project is discussing about the translation of "annotated tag" ( progit/progit2-zh#205 ).

Currently we have 3 options:
- 带附注标签
- 注释标签
- 注解标签

We can not make any agreement until now.  The community want to hear **your voice**, which is very important to us.

Once we make a decision, I can amend my commit in this PR accordingly.

Thanks.

**Comment by jiangxin** [comment]
@oldsharp, I have read your discussion on translation of annotated tag.
I think "附注标签" is a better translation.  So I cherry-picked your command,
and update translation of annotated tag to "附注标签".

Thank you

**Comment by oldsharp** [comment]
@jiangxin Thanks.

**Pull request merged**
